//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chalan_Detail
    {
        public int ChalanId { get; set; }
        public string Inv_Number { get; set; }
        public string Challan_No { get; set; }
        public Nullable<System.DateTime> Chalan_Date { get; set; }
        public string TP_Number { get; set; }
        public string Truck_Number { get; set; }
        public Nullable<decimal> Load_Quantity { get; set; }
        public Nullable<decimal> UL_Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Off_Expenses { get; set; }
        public Nullable<decimal> Cash_Adv { get; set; }
        public Nullable<decimal> Bank_Adv { get; set; }
        public Nullable<decimal> HSD_Adv { get; set; }
        public string Slip_No { get; set; }
        public string Petrol_Pump_Name { get; set; }
        public Nullable<decimal> Driver_Welfare { get; set; }
        public string Status { get; set; }
        public string Consignor { get; set; }
        public string Consignee { get; set; }
        public string Billing_Party { get; set; }
        public string Loading_Point { get; set; }
        public string Unloading_Point { get; set; }
        public string Truck_Owner_Name { get; set; }
        public string Address { get; set; }
        public string Driver_Name { get; set; }
        public string DL_Number { get; set; }
        public string Contact_No { get; set; }
        public string Ref_Number { get; set; }
        public Nullable<System.DateTime> Receive_Date { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string FromAccount { get; set; }
        public string ChequeNo { get; set; }
        public string BankCash { get; set; }
        public string ToAccount { get; set; }
        public string OtherPayment { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    }
}
