//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TMSEntities : DbContext
    {
        public TMSEntities()
            : base("name=TMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<VehicleMaster> VehicleMasters { get; set; }
        public virtual DbSet<VehicleOwner> VehicleOwners { get; set; }
        public virtual DbSet<vw_vehicle_master> vw_vehicle_master { get; set; }
        public virtual DbSet<vw_vehicle_owner> vw_vehicle_owner { get; set; }
        public virtual DbSet<NGT_Payment> NGT_Payment { get; set; }
        public virtual DbSet<vw_challan_detail> vw_challan_detail { get; set; }
        public virtual DbSet<Chalan_Detail> Chalan_Detail { get; set; }
    }
}
