//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_vehicle_master
    {
        public int OwnerId { get; set; }
        public string OwnerName { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleEncrypt { get; set; }
        public int VehicleId { get; set; }
    }
}
