//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_vehicle_owner
    {
        public int OwnerId { get; set; }
        public string OwnerEncrypt { get; set; }
        public string OwnerName { get; set; }
        public string Adress { get; set; }
        public string ContactNo { get; set; }
        public string PAN { get; set; }
        public string Email { get; set; }
    }
}
